obj-$(CONFIG_MACH_MSM8916_LGPS19) += board-8916-lgps19.o
obj-$(CONFIG_MACH_MSM8916_E2_GLOBAL_COM) += board-8916-e2.o
obj-$(CONFIG_MACH_MSM8916_E2DS_GLOBAL_COM) += board-8916-e2ds.o
obj-$(CONFIG_MACH_MSM8916_E2N_GLOBAL_COM) += board-8916-e2n.o

obj-$(CONFIG_MACH_LGE) += devices_lge.o


obj-$(CONFIG_LGE_PM) += lge_charging_scenario.o
obj-$(CONFIG_LGE_PM) += lge_gpio_debug.o
obj-$(CONFIG_LGE_PM) += lge_monitor_thermal.o
obj-$(CONFIG_LGE_BOOTLOADER_LOG) += lge_bootloader_log.o
obj-$(CONFIG_LGE_BOOTLOADER_TIME_CHECKER) += lge_bootloader_time_checker.o
obj-$(CONFIG_LGE_HANDLE_PANIC) += lge_handle_panic.o
obj-$(CONFIG_LCD_KCAL) += lge_kcal_ctrl.o
obj-$(CONFIG_PRE_SELF_DIAGNOSIS) += lge_pre_selfd.o

obj-$(CONFIG_LGE_QFPROM_INTERFACE) += lge_qfprom_access.o
